"""
Models module

Author: Brett Turner (ntounix-prog)
Created: November 2024
Copyright (c) 2024 Brett Turner. All rights reserved.
"""

from sqlalchemy import Column, Integer, String, Text, Boolean, DateTime, JSON, ForeignKey, Float
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from typing import Dict, Any, List, Optional
from datetime import datetime
from enum import Enum

from glassdome.core.database import Base


class AlertSeverity(str, Enum):
    """Severity levels for network alerts"""
    INFO = "info"           # Normal operational info
    WARNING = "warning"     # Degraded but functional
    ERROR = "error"         # Service impacted
    CRITICAL = "critical"   # Immediate action required


class AlertType(str, Enum):
    """Types of network alerts"""
    # Connectivity
    PING_FAILED = "ping_failed"
    PING_LATENCY = "ping_latency"
    GATEWAY_UNREACHABLE = "gateway_unreachable"
    DNS_FAILED = "dns_failed"
    
    # Network
    INTERFACE_DOWN = "interface_down"
    VLAN_LEAK = "vlan_leak"
    MAC_CHANGE = "mac_change"
    IP_CHANGE = "ip_change"
    
    # VM Health
    VM_UNREACHABLE = "vm_unreachable"
    VM_HIGH_LATENCY = "vm_high_latency"
    GUEST_AGENT_DOWN = "guest_agent_down"
    
    # Security
    UNEXPECTED_HOST = "unexpected_host"
    ARP_ANOMALY = "arp_anomaly"
    
    # System
    WHITEPAWN_DEPLOYED = "whitepawn_deployed"
    WHITEPAWN_STOPPED = "whitepawn_stopped"
    RECONCILIATION_DRIFT = "reconciliation_drift"


class WhitePawnDeployment(Base):
    """
    A WhitePawn monitoring instance deployed to a lab network.
    
    One WhitePawn per lab - monitors all networks and VMs in that lab.
    """
    __tablename__ = "whitepawn_deployments"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # What we're monitoring
    lab_id = Column(String(100), nullable=False, index=True, unique=True)
    lab_name = Column(String(255), nullable=True)
    
    # Deployment details
    deployment_type = Column(String(50), default="container")  # container, vm, agent
    host_vm_id = Column(String(100), nullable=True)  # VM hosting WhitePawn (if VM-based)
    host_ip = Column(String(50), nullable=True)  # IP of WhitePawn monitor
    
    # Configuration
    config = Column(JSON, nullable=True, default=dict)
    # config includes:
    # - ping_interval: seconds between ping sweeps (default 10)
    # - alert_threshold_ms: latency threshold for warnings (default 100)
    # - dns_check_interval: seconds between DNS checks (default 30)
    # - arp_scan_interval: seconds between ARP scans (default 60)
    
    # Networks being monitored
    monitored_networks = Column(JSON, nullable=True)  # List of network_ids
    
    # VMs being monitored
    monitored_vms = Column(JSON, nullable=True)  # List of vm_ids with IPs
    
    # State
    status = Column(String(50), default="pending")  # pending, deploying, active, stopped, error
    last_heartbeat = Column(DateTime, nullable=True)
    error_message = Column(Text, nullable=True)
    
    # Metrics
    total_checks = Column(Integer, default=0)
    total_alerts = Column(Integer, default=0)
    uptime_percent = Column(Float, default=100.0)
    
    # Metadata
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())
    
    # Relationships
    alerts = relationship("NetworkAlert", back_populates="deployment", cascade="all, delete-orphan")
    events = relationship("MonitoringEvent", back_populates="deployment", cascade="all, delete-orphan")
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "lab_id": self.lab_id,
            "lab_name": self.lab_name,
            "deployment_type": self.deployment_type,
            "host_vm_id": self.host_vm_id,
            "host_ip": self.host_ip,
            "config": self.config,
            "monitored_networks": self.monitored_networks,
            "monitored_vms": self.monitored_vms,
            "status": self.status,
            "last_heartbeat": self.last_heartbeat.isoformat() if self.last_heartbeat else None,
            "error_message": self.error_message,
            "total_checks": self.total_checks,
            "total_alerts": self.total_alerts,
            "uptime_percent": self.uptime_percent,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class NetworkAlert(Base):
    """
    An alert generated by WhitePawn monitoring.
    
    Alerts are generated when:
    - Connectivity issues detected
    - VMs become unreachable
    - Network anomalies found
    - Performance thresholds exceeded
    """
    __tablename__ = "network_alerts"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Link to deployment
    deployment_id = Column(Integer, ForeignKey("whitepawn_deployments.id"), nullable=False, index=True)
    
    # Alert details
    alert_type = Column(String(50), nullable=False)
    severity = Column(String(20), nullable=False, default=AlertSeverity.WARNING.value)
    
    # What's affected
    source_ip = Column(String(50), nullable=True)  # WhitePawn IP
    target_ip = Column(String(50), nullable=True)  # Affected target
    target_vm_id = Column(String(100), nullable=True)
    target_vm_name = Column(String(255), nullable=True)
    network_id = Column(Integer, nullable=True)
    
    # Alert content
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=True)
    details = Column(JSON, nullable=True)  # Additional structured data
    
    # Metrics (if applicable)
    latency_ms = Column(Float, nullable=True)
    packet_loss_percent = Column(Float, nullable=True)
    
    # State
    acknowledged = Column(Boolean, default=False)
    acknowledged_by = Column(String(100), nullable=True)
    acknowledged_at = Column(DateTime, nullable=True)
    
    resolved = Column(Boolean, default=False)
    resolved_at = Column(DateTime, nullable=True)
    auto_resolved = Column(Boolean, default=False)  # True if issue fixed itself
    
    # Metadata
    created_at = Column(DateTime, default=func.now())
    
    # Relationships
    deployment = relationship("WhitePawnDeployment", back_populates="alerts")
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "deployment_id": self.deployment_id,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "source_ip": self.source_ip,
            "target_ip": self.target_ip,
            "target_vm_id": self.target_vm_id,
            "target_vm_name": self.target_vm_name,
            "network_id": self.network_id,
            "title": self.title,
            "message": self.message,
            "details": self.details,
            "latency_ms": self.latency_ms,
            "packet_loss_percent": self.packet_loss_percent,
            "acknowledged": self.acknowledged,
            "resolved": self.resolved,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class MonitoringEvent(Base):
    """
    A monitoring event/check result from WhitePawn.
    
    Events are logged for every check (successful or not).
    Used for metrics, trends, and debugging.
    """
    __tablename__ = "monitoring_events"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Link to deployment
    deployment_id = Column(Integer, ForeignKey("whitepawn_deployments.id"), nullable=False, index=True)
    
    # Event type
    event_type = Column(String(50), nullable=False)  # ping, dns, arp, gateway, etc.
    
    # Target
    target_ip = Column(String(50), nullable=True)
    target_vm_id = Column(String(100), nullable=True)
    
    # Result
    success = Column(Boolean, nullable=False)
    latency_ms = Column(Float, nullable=True)
    error = Column(String(255), nullable=True)
    
    # Additional data
    details = Column(JSON, nullable=True)
    
    # Timestamp
    created_at = Column(DateTime, default=func.now(), index=True)
    
    # Relationships
    deployment = relationship("WhitePawnDeployment", back_populates="events")
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "deployment_id": self.deployment_id,
            "event_type": self.event_type,
            "target_ip": self.target_ip,
            "target_vm_id": self.target_vm_id,
            "success": self.success,
            "latency_ms": self.latency_ms,
            "error": self.error,
            "details": self.details,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class ConnectivityMatrix(Base):
    """
    Stores the connectivity matrix between VMs in a lab.
    
    Updated every monitoring cycle with ping results between all VMs.
    """
    __tablename__ = "connectivity_matrix"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Link to deployment
    deployment_id = Column(Integer, ForeignKey("whitepawn_deployments.id"), nullable=False, index=True)
    lab_id = Column(String(100), nullable=False, index=True)
    
    # The matrix data
    # Format: {"vm1_ip": {"vm2_ip": {"reachable": true, "latency_ms": 1.2}, ...}, ...}
    matrix = Column(JSON, nullable=False)
    
    # Summary
    total_pairs = Column(Integer, default=0)
    reachable_pairs = Column(Integer, default=0)
    avg_latency_ms = Column(Float, nullable=True)
    max_latency_ms = Column(Float, nullable=True)
    
    # Timestamp
    created_at = Column(DateTime, default=func.now())
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "deployment_id": self.deployment_id,
            "lab_id": self.lab_id,
            "matrix": self.matrix,
            "total_pairs": self.total_pairs,
            "reachable_pairs": self.reachable_pairs,
            "avg_latency_ms": self.avg_latency_ms,
            "max_latency_ms": self.max_latency_ms,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

